### ISSUE TITLE
N1 媒体服务器Docker镜像 | 某不科学的博客

### ISSUE THREAD

**Issue by Taosky** [Taosky/taosky.github.io#57]
https://taosky.github.io/post/n1-media-server-docker/

**Comment by jsionylynn** [comment]
n1-media-server pull 不了

**Comment by Taosky** [comment]
> @jsionylynn
> n1-media-server pull 不了
> 

太久远了，dockerhub账号都删了😅😅，可以单独安装transmission和alist的镜像试试。
